/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-25 01:20:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/GitHub/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webExam2/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308094570000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1591002330163L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<title>Buddit Management</title>\n");
      out.write("<script src=\"https://kit.fontawesome.com/75beac86c5.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<nav class=\"navbar navbar-light mb-2\" style=\"background-color:#6d844d;\">\n");
      out.write("  \t\t<a class=\"navbar-brand\" href=\"#\">\n");
      out.write("    \t<img src=\"reg.png\" width=\"auto\" height=\"32\"></a>\n");
      out.write("  \t\t<a class=\"page-link text-dark bg-light\" href=\"#\">\n");
      out.write("  \t\t<i class=\"fas fa-user-circle\"></i>管理者 様</a>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t  <div class=\"col-3\">\n");
      out.write("\t    \n");
      out.write("\t      <form action=\"ManageServlet\" method=\"get\">\n");
      out.write("\t      \t<button name=\"init\" class=\"btn btn-primary btn-block\">\n");
      out.write("\t      \t<i class=\"fas fa-home\"></i>ホーム</button>\n");
      out.write("\t      </form>\n");
      out.write("\t      \n");
      out.write("\t\t  <div class=\"accordion\" id=\"productAccordion\">\n");
      out.write("\t\t\t     <div class=\"card\">\n");
      out.write("\t\t\t     \n");
      out.write("\t\t\t        <div class=\"card-header\">\n");
      out.write("\t\t\t          <a class=\"text-dark d-block p-3 m-n3\" data-toggle=\"collapse\" href=\"#productCollapse\">\n");
      out.write("\t\t\t          <i class=\"fas fa-cube\"></i>商品管理</a>\n");
      out.write("\t\t\t        </div>\n");
      out.write("\t\t\t        \n");
      out.write("\t\t\t        <div class=\"collapse show\" id=\"productCollapse\" data-parent=\"#productAccordion\">\n");
      out.write("\t\t\t        \n");
      out.write("\t\t\t\t        <div class=\"card-body\">\n");
      out.write("\t\t\t\t        \n");
      out.write("\t\t\t\t        \t<form action=\"ManageServlet\" method=\"get\">\n");
      out.write("\t      \t\t\t\t\t\t<button name=\"btn\" value=\"search\" class=\"btn btn-outline-success btn-block\">商品一覧</button>\n");
      out.write("\t      \t\t\t\t\t\t<input type=\"hidden\" name=\"selectWay\" value=\"all\">\n");
      out.write("\t     \t\t\t\t\t</form>\n");
      out.write("\t      \n");
      out.write("\t\t\t\t      \t\t<form action=\"ManageServlet\" method=\"get\">\n");
      out.write("\t\t\t\t\t\t\t\t<button name=\"btn\" value=\"insert\" class=\"btn btn-outline-success btn-block\">商品登録</button>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t      \t\t\n");
      out.write("\t     \t \t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  \n");
      out.write("\t\t  <form action=\"ManageServlet\" method=\"get\">\n");
      out.write("\t      \t\t<button name=\"btn\" value=\"search\" class=\"btn btn-info btn-block\">売上管理</button>\n");
      out.write("\t      \t\t<input type=\"hidden\" name=\"selectWay\" value=\"sales\">\n");
      out.write("\t     </form>\n");
      out.write("\t     \t \n");
      out.write("\t      <div class=\"accordion\" id=\"searchAccordion\">\n");
      out.write("\t\t     <div class=\"card\">\n");
      out.write("\t\t     \n");
      out.write("\t\t        <div class=\"card-header\">\n");
      out.write("\t\t          <a class=\"text-dark d-block p-3 m-n3\" data-toggle=\"collapse\" href=\"#searchCollapse\">\n");
      out.write("\t\t\t\t  <i class=\"fas fa-search-plus\"></i>検索条件</a>\n");
      out.write("\t\t        </div>\n");
      out.write("\t\t        \n");
      out.write("\t\t        <div class=\"collapse show\" id=\"searchCollapse\" data-parent=\"#searchAccordion\">\n");
      out.write("\t\t        \n");
      out.write("\t\t\t        <div class=\"card-body\">\n");
      out.write("\t\t\t        \n");
      out.write("\t\t\t\t     \t<form action=\"ManageServlet\" method=\"get\">\n");
      out.write("\t\t\t     \t\t\t<div class=\"form-group\">\n");
      out.write("\t\t                    \t<label for=\"Name\">Search Name</label>\n");
      out.write("\t\t\t                    \t<div class=\"form-row align-items-center\">\n");
      out.write("\t\t\t                    \t\n");
      out.write("\t\t\t                    \t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t                    \t\t\t<input type=\"text\" name=\"name\" class=\"form-control\" id=\"Name\" placeholder=\"テキスト入力欄\">\n");
      out.write("\t\t\t                    \t\t</div>\n");
      out.write("\t\t\t                    \t\t\n");
      out.write("\t\t\t                    \t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t                    \t\t\t<button name=\"btn\" value=\"search\">検索</button>\n");
      out.write("\t\t\t                    \t\t\t<input type=\"hidden\" name=\"selectWay\" value=\"name\">\n");
      out.write("\t\t\t                    \t\t</div>\n");
      out.write("\t\t\t                    \t\t\n");
      out.write("\t\t\t                  \t\t</div>\n");
      out.write("\t\t\t                </div>\n");
      out.write("\t\t\t            </form>\n");
      out.write("\t\t\t            \n");
      out.write("\t\t\t            <form action=\"ManageServlet\" method=\"get\">    \n");
      out.write("\t\t\t                <div class=\"form-group\">\n");
      out.write("\t\t                    \t<label for=\"Category\">Search Category</label>\n");
      out.write("\t\t\t                    \t<div class=\"form-row align-items-center\">\n");
      out.write("\t\t\t                    \t\n");
      out.write("\t\t\t                    \t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t                    \t\t\t<select name=\"category\" class=\"form-control\" id=\"Category\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <option value=\"general\">雑貨</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"electric\">家電</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"book\">書籍</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"food\">食品</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"fashion\">ファッション</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"other\">未分類</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </select>\n");
      out.write("\t\t\t                    \t\t</div>\n");
      out.write("\t\t\t                    \t\t\n");
      out.write("\t\t\t                    \t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t                    \t\t\t<button name=\"btn\" value=\"search\">検索</button>\n");
      out.write("\t\t\t                    \t\t\t<input type=\"hidden\" name=\"selectWay\" value=\"category\">\n");
      out.write("\t\t\t                    \t\t</div>\n");
      out.write("\t\t\t                    \t\t\n");
      out.write("\t\t\t                  \t\t</div>\n");
      out.write("\t\t\t                </div>\n");
      out.write("\t\t\t            </form>\n");
      out.write("\t\t\t            \n");
      out.write("\t\t\t            <form action=\"ManageServlet\" method=\"get\">  \n");
      out.write("\t\t\t                <div class=\"form-group\">\n");
      out.write("\t\t                    \t<label for=\"Price\">Search Price</label>\n");
      out.write("\t\t\t                    \t<div class=\"form-row align-items-center\">\n");
      out.write("\t\t\t                    \t\n");
      out.write("\t\t\t                    \t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t                    \t\t\t<select name=\"price\" class=\"form-control\" id=\"Price\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <option value=\"0\">0-1500円</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">1500-3000円</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">3000-5000円</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">5000-10000円</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\">10000円以上</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </select>\n");
      out.write("\t\t\t                    \t\t</div>\n");
      out.write("\t\t\t                    \t\t\n");
      out.write("\t\t\t                    \t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t                    \t\t\t<button name=\"btn\" value=\"search\">検索</button>\n");
      out.write("\t\t\t                    \t\t\t<input type=\"hidden\" name=\"selectWay\" value=\"price\">\n");
      out.write("\t\t\t                    \t\t</div>\n");
      out.write("\t\t\t                    \t\t\n");
      out.write("\t\t\t                  \t\t</div>\n");
      out.write("\t\t\t                </div>\n");
      out.write("\t\t\t\t        </form>\n");
      out.write("\t      \t\t\t</div>\n");
      out.write("\t      \t\t</div>\n");
      out.write("\t    \t </div>  \n");
      out.write("\t       </div>\n");
      out.write("\t  </div>\n");
      out.write("\t  \n");
      out.write("\t  <div class=\"col-9\">\n");
      out.write("\t    \n");
      out.write("\t      ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t  \n");
      out.write("\t\t  ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t   </div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\" integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /manage.jsp(146,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t        <table class=\"table table-striped\">\n");
          out.write("\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t<th>商品id</th><th>商品コード</th><th>商品名</th><th>カテゴリ</th><th>価格</th><th>在庫</th><th></th><th></th><th></th>\n");
          out.write("\t\t\t\t</tr>\n");
          out.write("\t\t\t\t\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t</table>\n");
          out.write("\t\t  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /manage.jsp(152,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /manage.jsp(152,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/manage.jsp(152,4) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t<tr>\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t<td>\n");
            out.write("\t\t\t\t\t\t\t<form action=\"ManageServlet\" method=\"get\">\n");
            out.write("\t\t\t\t\t\t\t\t<button name=\"btn\" value=\"edit\">変更</button>\n");
            out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"code\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("\t\t\t\t\t\t\t</form>\n");
            out.write("\t\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t\t<td>\n");
            out.write("\t\t\t\t\t\t\t<form action=\"ManageServlet\" method=\"get\">\n");
            out.write("\t\t\t\t\t\t\t\t<button name=\"btn\" value=\"stock\">補充</button>\n");
            out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"code\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("\t\t\t\t\t\t\t</form>\n");
            out.write("\t\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t\t<td>\n");
            out.write("\t\t\t\t\t\t\t<form action=\"ManageServlet\" method=\"get\">\n");
            out.write("\t\t\t\t\t\t\t\t<button name=\"btn\" value=\"delete\">削除</button>\n");
            out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"code\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("\t\t\t\t\t\t\t</form>\n");
            out.write("\t\t\t\t\t\t</td>\n");
            out.write("\t\t\t\t\t</tr>\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /manage.jsp(178,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list2 != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t<h4>売上数を表示しています</h4>\n");
          out.write("\t\t\t\t<table class=\"table table-striped\">\n");
          out.write("\t\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t\t<th>商品id</th><th>商品コード</th><th>商品名</th><th>カテゴリ</th><th>売上</th>\n");
          out.write("\t\t\t\t\t</tr>\n");
          out.write("\t\t\t\t\t\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t</table>\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /manage.jsp(185,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("item");
      // /manage.jsp(185,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/manage.jsp(185,5) '${list2}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list2}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t<tr>\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td><td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.sales}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t</tr>\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
